"""add cut drug and discount support

Revision ID: 2a461ef64446
Revises: 7b06517c21c3
Create Date: 2026-05-28 23:14:55.406110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a461ef64446'
down_revision: Union[str, None] = '7b06517c21c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shifts_id', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index('ix_stock_movements_id', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_void_requests_id', table_name='void_requests')
    op.drop_table('void_requests')
    op.add_column('products', sa.Column('is_cuttable', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('sub_unit', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('pieces_per_unit', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('sub_quantity_sold', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('sub_unit', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.alter_column('sales', 'quantity_sold',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'quantity_sold',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sales', 'discount_amount')
    op.drop_column('sales', 'sub_unit')
    op.drop_column('sales', 'sub_quantity_sold')
    op.drop_column('products', 'pieces_per_unit')
    op.drop_column('products', 'sub_unit')
    op.drop_column('products', 'is_cuttable')
    op.create_table('void_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='void_requests_sale_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='void_requests_pkey')
    )
    op.create_index('ix_void_requests_id', 'void_requests', ['id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_changed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_movements_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_movements_stock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_movements_pkey')
    )
    op.create_index('ix_stock_movements_id', 'stock_movements', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opened_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('closed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_sales', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('pos_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('cash_expected', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('cash_counted', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('variance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['user.id'], name='shifts_closed_by_fkey'),
    sa.ForeignKeyConstraint(['opened_by'], ['user.id'], name='shifts_opened_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='shifts_pkey')
    )
    op.create_index('ix_shifts_id', 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###
