"""add shifts table

Revision ID: 30af815cc40e
Revises: ffdd3b31f58a
Create Date: 2026-05-22 08:41:06.082695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30af815cc40e'
down_revision: Union[str, None] = 'ffdd3b31f58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_void_requests_id', table_name='void_requests')
    op.drop_table('void_requests')
    op.drop_index('ix_stock_movements_id', table_name='stock_movements')
    op.drop_table('stock_movements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_changed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_movements_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_movements_stock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_movements_pkey')
    )
    op.create_index('ix_stock_movements_id', 'stock_movements', ['id'], unique=False)
    op.create_table('void_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='void_requests_sale_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='void_requests_pkey')
    )
    op.create_index('ix_void_requests_id', 'void_requests', ['id'], unique=False)
    # ### end Alembic commands ###
