"""add txn_id to sales

Revision ID: 8383102950f1
Revises: 0eda63566950
Create Date: 2026-05-24 22:58:13.677985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8383102950f1'
down_revision: Union[str, None] = '0eda63566950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_void_requests_id', table_name='void_requests')
    op.drop_table('void_requests')
    op.drop_index('ix_stock_movements_id', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_shifts_id', table_name='shifts')
    op.drop_table('shifts')
    op.add_column('sales', sa.Column('txn_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sales_txn_id'), 'sales', ['txn_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_txn_id'), table_name='sales')
    op.drop_column('sales', 'txn_id')
    op.create_table('shifts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opened_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('closed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_sales', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('pos_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('cash_expected', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('cash_counted', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('variance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['user.id'], name='shifts_closed_by_fkey'),
    sa.ForeignKeyConstraint(['opened_by'], ['user.id'], name='shifts_opened_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='shifts_pkey')
    )
    op.create_index('ix_shifts_id', 'shifts', ['id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_changed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_movements_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_movements_stock_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_movements_pkey')
    )
    op.create_index('ix_stock_movements_id', 'stock_movements', ['id'], unique=False)
    op.create_table('void_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='void_requests_sale_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='void_requests_pkey')
    )
    op.create_index('ix_void_requests_id', 'void_requests', ['id'], unique=False)
    # ### end Alembic commands ###
