"""sales: quantity_sold to numeric, txn_id uniqueness scoped to stock_id

Revision ID: ad8b853cd9ce
Revises: b152e8f4588d
Create Date: 2026-07-05 21:29:37.231089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8b853cd9ce'
down_revision: Union[str, None] = 'b152e8f4588d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'quantity_sold',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index('ix_sales_txn_id', table_name='sales')
    op.create_index(op.f('ix_sales_txn_id'), 'sales', ['txn_id'], unique=False)
    op.create_unique_constraint('uq_sales_txn_id_stock_id', 'sales', ['txn_id', 'stock_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sales_txn_id_stock_id', 'sales', type_='unique')
    op.drop_index(op.f('ix_sales_txn_id'), table_name='sales')
    op.create_index('ix_sales_txn_id', 'sales', ['txn_id'], unique=True)
    op.alter_column('sales', 'quantity_sold',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
