"""add void columns to sales

Revision ID: c51d6f89d207
Revises: 0002_stock_reconciliations
Create Date: 2026-05-07 12:01:53.731285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51d6f89d207'
down_revision: Union[str, None] = '0002_stock_reconciliations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('is_voided', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sales', sa.Column('void_reason', sa.String(length=500), nullable=True))
    op.add_column('sales', sa.Column('voided_by', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_recon_date', table_name='stock_reconciliations')
    op.drop_index('ix_recon_product_id', table_name='stock_reconciliations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recon_product_id', 'stock_reconciliations', ['product_id'], unique=False)
    op.create_index('ix_recon_date', 'stock_reconciliations', ['recon_date'], unique=False)
    op.drop_column('sales', 'voided_at')
    op.drop_column('sales', 'voided_by')
    op.drop_column('sales', 'void_reason')
    op.drop_column('sales', 'is_voided')
    # ### end Alembic commands ###
