"""add stock_movements table

Revision ID: ffdd3b31f58a
Revises: d74832d5cf0a
Create Date: 2026-05-12 19:35:29.619845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffdd3b31f58a'
down_revision: Union[str, None] = 'd74832d5cf0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_void_requests_id', table_name='void_requests')
    op.drop_table('void_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('void_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='void_requests_sale_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='void_requests_pkey')
    )
    op.create_index('ix_void_requests_id', 'void_requests', ['id'], unique=False)
    # ### end Alembic commands ###
